# Generated by Django 5.1.6 on 2025-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
